import lancedb
from lancedb.pydantic import LanceModel, Vector
from pydantic import Field
import os
from pathlib import Path

# --- CONFIGURATION ---
# Dynamically resolve the project root to ensure this works
# regardless of where the script is called from.
# Logic: This file is in src/common/, so we go up 3 levels to find the root.
BASE_DIR = Path(__file__).resolve().parent.parent.parent
DB_PATH = os.path.join(BASE_DIR, "data", "lancedb_store")

# Ensure the data directory exists before we try to connect
os.makedirs(DB_PATH, exist_ok=True)

# --- SCHEMA DEFINITION ---
class Document(LanceModel):
    """
    The Master Schema for our Document Database.
    Inherits from LanceModel to allow seamless integration with LanceDB.
    """
    # Primary Key: The SHA/xxHash of the file content.
    # This ensures that renaming a file doesn't create a duplicate.
    id: str = Field(pk=True)

    # Metadata Fields
    filename: str
    file_path: str
    file_type: str  # e.g., 'pdf', 'jpg'
    file_size_bytes: int
    creation_date: float
    last_modified: float

    # --- AI FIELDS ---
    # Vector: A list of floats representing the semantic meaning.
    # 384 dimensions is the standard output size for 'all-MiniLM-L6-v2'.
    # We default to a zero-vector so we can insert metadata FIRST, and embed LATER.
    vector: Vector(384) = Field(default=[0.0] * 384)

    # Summary: The text summary generated by the LLM (Phase 2/3)
    summary: str = Field(default="")

    # Category: The folder classification (Phase 3)
    category: str = Field(default="Unsorted")


# --- DATABASE CONNECTION ---
def get_table(table_name="documents"):
    """
    Connects to the embedded LanceDB instance and retrieves the requested table.
    Safely creates the table if it does not exist.
    """
    db = lancedb.connect(DB_PATH)

    # Check if table exists to avoid 'ValueError' in newer LanceDB versions.
    # We prioritize safety over 'try/catch' blocks here.
    if table_name in db.table_names():
        table = db.open_table(table_name)
    else:
        # Create a new table using the Pydantic Schema defined above
        table = db.create_table(table_name, schema=Document)

    return table